# Generated by Django 4.1.5 on 2023-01-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsApp', '0002_alter_issue_assignee_user_alter_issue_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('elevee', 'Elevée')], max_length=6),
        ),
    ]
